apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - monitoring.yaml
  - app.yaml
  - cert-manager.yaml
  - vault.yaml
  - falco.yaml
  - kyverno.yaml
  - sealed-secrets.yaml
  - gatekeeper-system.yaml
  - infrastructure.yaml
  - longhorn-system.yaml
  - harbor.yaml
  - istio-system.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: falco
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: sealed-secrets
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    managed-by: argocd
