apiVersion: v2
name: vault
description: A Helm chart for HashiCorp Vault - Secrets management
type: application
version: 1.0.0
appVersion: "1.17.0"
keywords:
  - vault
  - secrets
  - secret-management
  - encryption
maintainers:
  - name: Kubernetes Platform Stack
dependencies:
  - name: vault
    version: "0.28.0"
    repository: "https://helm.releases.hashicorp.com"
