apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

# Configure CoreDNS resource limits and image version
# The Deployment itself is created by KIND; we only manage the configuration patch
resources:
  - coredns-configpatch.yaml
